### ISSUE TITLE
hidden state creation

### ISSUE THREAD

**Issue by aa1607** [jihunchoi/hyperlstm#1]
Hi, I was looking through your code to try and understand hypernets. (Really nice implementation of the tensorflow model btw). I spent a bit of time trying it out and just wanted to point this out:

 state = (zero_state, zero_state)

I think in Python this means that your cell state and hidden state actually refer to the same object. This would obviously be a huge problem because at each step you're modifiying the cell state at operations where you should only be modifying the hidden state h.

This is uglier but probably safer:

    def forward(self, x, state):
        if state is None:
            batch_size , hidden_size = x.size(0), self.hidden_size
            h = Variable(x.data.new_zeros([batch_size, hidden_size])
            c = Variable(x.data.new_zeros([batch_size, hidden_size])
            state = (h, c)

**Comment by jihunchoi** [comment]
Hmm I don't think that could be a problem, since they refer to the same object only at the initial computation.
The first new_h and new_c share the same parent (zero_state), but it is a leaf variable that isn't updated during training thus I think the current implementation work as expected.

nn.LSTMCell also implements the initial state in the similar way to this repo's: https://github.com/pytorch/pytorch/blob/42001e7c17ffa80c00377ab9d07650241fa4713f/torch/nn/modules/rnn.py#L725-L726

**Comment by aa1607** [comment]
Hey I just checked the link you sent me and you're right, although I'm still not sure at what point the objects become distinct if they're initialized as the same variables. Either way though sorry for the false alarm!

**Comment by jihunchoi** [comment]
I'm not aware of the exact internal implementation, but as far as I know the computation graph (DAG-like) is constructed dynamically as the forward computation goes. Thus at the end of the same iteration t=0, the hidden and the memory state will be distinct variables having the identical parent (or ancestor)!
